name: example-workflow

on: [push]

jobs:
  production-deploy:

      runs-on: ubuntu-latest

      name: Example Workflow

      steps:

      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      - run: npm run lint (Run ESLint)

      - run: npm run test (Run Jest)